services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: technews
    ports:
      - "5432:5432"
  test_db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: technews_test
    ports:
      - "5433:5432" # Different port to avoid conflict
  backend:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
    depends_on:
      - db
